fish_config theme choose kanagawa

# Alias
alias vim='nvim'

# Path settings
export PATH="$HOME/.deno/bin:$PATH"
export PATH="/opt/homebrew/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

# PNPM
set -gx PNPM_HOME /Users/hwisookim/Library/pnpm
if not string match -q -- $PNPM_HOME $PATH
    set -gx PATH "$PNPM_HOME" $PATH
end

# Pyenv
set -gx PYENV_ROOT "$HOME/.pyenv"
if test -d "$PYENV_ROOT/bin"
    set -gx PATH "$PYENV_ROOT/bin" $PATH
    status --is-interactive; and pyenv init - | source
end

# Load environment variables from .env
if test -f "$HOME/.env"
    # Parse and load environment variables from .env
    for line in (cat "$HOME/.env")
        set line (string trim $line)
        if test -n "$line" && not string match -q "#*" $line
            set -l kv (string split -m 1 = $line)
            if test (count $kv) -eq 2
                set -l key (string trim $kv[1])
                # Remove 'export ' prefix if present
                set key (string replace -r '^export ' '' $key)
                set -l val (string trim --chars=\'\" $kv[2])
                set -gx $key $val
            end
        end
    end
end

# Custom prompt
function fish_prompt
    set_color yellow
    echo -n '><3> '
    echo -n (prompt_pwd)
    echo -n ' ; '
end

# Ghostty integration
if set -q GHOSTTY_RESOURCES_DIR
    source "$GHOSTTY_RESOURCES_DIR/shell-integration/fish/vendor_conf.d/ghostty-shell-integration.fish"
end

if status is-interactive
    set original (fortune)
    set translated (echo $original | trans -b :ko)
    echo -e "Original:\n$original\n\nTranslated:\n$translated" | ~/quokka-say/target/release/quokka-say | lolcat -a -d 1 -s 50 -p 1 -F 0.3 -f
end

# Source environment variables generated by .gen_envs.fish
source ~/.gen_envs.fish
